### ISSUE TITLE
can i get source code?

### ISSUE THREAD

**Issue by JokerJohn** [hatem-darweesh/assuremappingtools#11]
hello hatem, thanks for your hard work!
i saw your code in Autoware, in the op_planner  and servial nodes, it supports kml map and vector map. i wonder whether i can get the source code of assuremappingtools for learning?

**Comment by hatem-darweesh** [comment]
@JokerJohn , The code for the tools uses op_planner functions, only wrap it in OpenGL interface. 
so you can find all what you need in the op_planner source code.
I am afraid the source code for the tools is not public for now.
