### ISSUE TITLE
How to make  HD map

### ISSUE THREAD

**Issue by Shelfcol** [hatem-darweesh/assuremappingtools#13]
I saw your tutorial video on youtube.But I want to know how to use a integrated navigation system and a velodyne lidar on one car to make HD map, such as  the lidar msgs topic, and the GPS topic name, to project local pointcloud2 to global coordinate.

**Comment by hatem-darweesh** [comment]
@Shelfcol sorry for the late reply, 
Although this is out of the scope of ASSURE mapping tool. but I can give you some hints. 

1. Collect sensor data and create rosbag , that includes LIDAR, GPS, IMU, CAN and Camera 
2. Use cloud mapping tools such as 
https://tools.tier4.jp/
https://www.youtube.com/watch?v=ss6Blrz23h8
3. After creating a point cloud map .pcd file(s) you can load it into ASSURE mapping tools and create your HD Map
