### ISSUE TITLE
Additional lane information is being added to the Lanelet2 map data 

### ISSUE THREAD

**Issue by RyanHuang0222** [hatem-darweesh/assuremappingtools#14]
Hi Mr. Hatem,

- Steps:
1. Covert the lanelet2 map(provided by [AutowareArchitectureProposal](https://drive.google.com/open?id=1ovrJcFS5CZ2H51D8xVWNtEvj_oiXW-zk)) to ADAS map by [lanelet_aisan_converter](https://gitlab.com/autowarefoundation/autoware.ai/utilities/-/tree/d415534fb4e53f6559261cb77d93ab75dd4d6eaf/lanelet_aisan_converter)
2. I confirm the ADAS map can be used to make plan in Autoware 1.3
3. I reconvert the ADAS map to lanelet2 map by the [assuremappingtools](https://github.com/hatem-darweesh/assuremappingtools)

- Issues:
1. The converted lanelet2 map can be used to make plan but most of the artifacts except road are missing, like traffic light...etc..
2. Comparing the [original map](https://drive.google.com/file/d/1BVpxOdQF1BjpxzFvuYO-lhtPCe-7z8NX/view?usp=sharing) vs. the [converted map](https://drive.google.com/file/d/1oe6o8KbzhisjRsYs-y-6mO2F8B-TcN9h/view?usp=sharing), it seems that additional lane information is being added to the Lanelet2 map data by the ASSURE Mapping tool.

Moverover, I also used assuremappingtools to convert my own ADAS map. The most of the artifacts are missing as well. But I am not sure whether the lane is perfectly converted. [Example](https://drive.google.com/drive/folders/1v_I9vE741xnutWyouxgSbRPsExAEztib?usp=sharing)

**Comment by hatem-darweesh** [comment]
@RyanHuang0222 currently this tool is underdevelopment, due to the lack of man power, I can't cover all features. 
the design and solution are available, but no time to code or test. 

if you need a specific simple solution which can make your life easier, let me know.
