### ISSUE TITLE
Projection string for Carla XODR maps?

### ISSUE THREAD

**Issue by travelbureau** [hatem-darweesh/assuremappingtools#15]
Hi I'm wondering if you have any hints for what projection string to use for the Carla maps if the eventual goal is to save in Autoware compatible lanelet2 format... 
Thanks for making this project available!

**Comment by hatem-darweesh** [comment]
Hi @travelbureau , I don't think you need projection for CARLA maps, they have and origin of (0,0,0) related to the simulation environment. 

Other OpenDRIVE maps from real world places needs projection string, it should be added to the projection tag in the beginning of the .xodr map file.
