### ISSUE TITLE
Please update to opencv 3.2.0 version or above

### ISSUE THREAD

**Issue by FajunChen** [hatem-darweesh/assuremappingtools#17]
It is not easy to install opencv 2.4 on Ubuntu 1806. If possible could you please update your opencv vesion to a the default 3.2.0 version or above? Thank you for you contribution.

**Comment by hatem-darweesh** [comment]
Did you tried the branch https://github.com/hatem-darweesh/assuremappingtools/tree/ubuntu18.04_build
$ git checkout ubuntu18.04_build

**Comment by FajunChen** [comment]
Thank you for your reply. There is no problem after checking out the ubuntu1804_build branch. 

I have another problem then. Could this tool extract  lanelet2 infomation from point cloud flie? From your tutorial video, I see that your lanelet2 file is loaded by hand, which is not converted from the pointcloud file. Thank you for you contribution.

**Comment by hatem-darweesh** [comment]
PointCloud map doesn't have Road network map information. not lanelet2 or any other HD map format
but what happen is we manually draw the map and save it to any format we wish. 
in assure mapping tools there are some automation functions that can help make the map creation process faster.

**Comment by FajunChen** [comment]
Could you please give me some promption about how to use those automationi functions? Or do you have any examples? Thanks.

**Comment by hatem-darweesh** [comment]
check youtube tutorials https://youtu.be/lignj-gVGVg

**Comment by FajunChen** [comment]
Cool, thanks. Do you have any plan to open the sources of your tools? Maybe someone others could improve it with you together, providing things such as better UI.

**Comment by hatem-darweesh** [comment]
Thank your suggestion, maybe in the future.
