### ISSUE TITLE
undefined symbol: _ZN10PlannerHNS11RoadNetwork13g_max_curb_idE

### ISSUE THREAD

**Issue by xqrkushnir** [hatem-darweesh/assuremappingtools#20]
Hi @hatem-darweesh ! I'm getting this error when trying to launch assure_map editor:
```
me: ~/Desktop/assuremappingtools$ ./assure_map_editor 

./assure_map_editor: symbol lookup error: ./assure_map_editor: 
undefined symbol: _ZN10PlannerHNS11RoadNetwork13g_max_curb_idE
```
I'm on Ubuntu 18, followed the README from the ubuntu18 branch. 
What can cause it? 
Regards, Andres

**Comment by hatem-darweesh** [comment]
It seems you have mixed library versions. 
please clean the lib directory , pull again and use export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:libs

**Comment by xqrkushnir** [comment]
Unfortunately, that didn't help. 

I've reinstalled and rebuilt OpenCV 2.4, removed and installed back all the dependent packages, and did "_export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:libs_". Also, restarted my PC, just in case.

**Comment by hatem-darweesh** [comment]
This issue has nothing to do with OpenCV. 
op_planner.so is wrong version. 
can you check after cloning that you are on the correct branch.

**Comment by xqrkushnir** [comment]
Sure!

```
me:~/Desktop/assuremappingtools$ git fetch 
me:~/Desktop/assuremappingtools$ git status
On branch ubuntu18.04_build
Your branch is up to date with 'origin/ubuntu18.04_build'.

nothing to commit, working tree clean

me:~/Desktop/assuremappingtools$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:libs
me:~/Desktop/assuremappingtools$ ./assure_map_editor 
./assure_map_editor: symbol lookup error: ./assure_map_editor: undefined symbol: 
_ZN10PlannerHNS11RoadNetwork13g_max_curb_idE
```

**Comment by xqrkushnir** [comment]
The issue covers somewhere within a conflicted package with Autoware.
With removing sourcing of Autoware's setup.sh from my **.bashrc**, I can launch the software without any issues.

The line I commented was this one:
``` source ~/autoware/devel/setup.bash ```

Just having ``` source /opt/ros/melodic/setup.bash ``` does the trick.
