### ISSUE TITLE
How to adjust distances between two neighborhood lane?

### ISSUE THREAD

**Issue by FajunChen** [hatem-darweesh/assuremappingtools#25]
Ideally, two neighborhood lane should share the middle line after converting to the lanelet2 format. However, as I tried the tool, it will generate two sperate lanes with seperate boarder. Could you please tell me how to draw a vector map in a correct manner?

**Comment by hatem-darweesh** [comment]
Thanks for your feedback, 
Yes, I am aware of this behavior, kml -> lanelet2 now is far from perfect. this issue is already included in the tasks list.
