### ISSUE TITLE
OpenDRIVE maps import issue

### ISSUE THREAD

**Issue by mpechinger** [hatem-darweesh/assuremappingtools#26]
First of all, thanks for providing the possibility to convert OpenDRIVE maps into a compatible format to be used in autoware.ai! I want to kindly ask you, if you can have another look into the problem described in #10

I have done as you have said in this issue, but I am still not able to resolve the problem. What I have tried so far:

- Installing assure mapping tools on Ubuntu 16.04 step by step strictly following the instruction steps one to four.

- I did this procedure twice to make sure I get the same result and didn't do anything wrong by accident. 

- I have applied the same procedure for the Ubuntu 18.04 installation. Following the steps and installing it twice.

- Every installation was performed on a fresh Linux installation in a virtual machine. The files I have used to test the functionality of the import tool were the sample files from opendrive.org. 

Since this is the only tool, I'm aware of, which provides the interface to OpenDRIVE maps I want to reopen the discussion on this problem I am experiencing. Thanks for your hard work, I really appreciate it!

![git_issue](https://user-images.githubusercontent.com/17145987/88635831-7264f400-d0b8-11ea-932c-e8d1038bf321.PNG)

**Comment by hatem-darweesh** [comment]
Sorry, I have to comment similarly. 
I couldn't reproduce this issue on any of my computers neither virtual machine.
but I will try to provide a docker image soon, so you don't have to install anything.

**Comment by mpechinger** [comment]
Thanks for the quick reply. A docker image would be really nice!
