### ISSUE TITLE
Is it possible to save vector maps in Aisan map format (for use with Autoware)?

### ISSUE THREAD

**Issue by LalithVipulananthan** [hatem-darweesh/assuremappingtools#29]
As per the title, I just wanted to check to see if it is possible to save vector maps in the Aisan format for use with Autoware. Thank you!

**Comment by hatem-darweesh** [comment]
I am sorry, AISAN format is not open standards. 
but you can use the exported lanelet2 or the .kml with Autoware.AI

**Comment by LalithVipulananthan** [comment]
Thank you very much for the prompt answer! 😄
