### ISSUE TITLE
Cannot save in autoware vector map format

### ISSUE THREAD

**Issue by Louis-Wong** [hatem-darweesh/assuremappingtools#3]
Hi @hatem-darweesh ,thanks for this tool. After I drawing the lane, I cannot save in the vector map format. It seems that it doesn't support this format currently.

**Comment by hatem-darweesh** [comment]
@Louis-Wong, currently working on the format writers, Hopefully by the end of September.

**Comment by shaobodang** [comment]
Hi @hatem-darweesh, any update on exporter?

**Comment by hatem-darweesh** [comment]
@shaobodang vector map saving and lanelet2 will come with the next release  hopefully end of November.

**Comment by hatem-darweesh** [comment]
@Louis-Wong Now the mapping tools can save lanelet2 for autoware. 
kindly give it a try.
