### ISSUE TITLE
How to connect between light-lane-stopline?

### ISSUE THREAD

**Issue by kyujinChoi** [hatem-darweesh/assuremappingtools#32]
Hi @hatem-darweesh 

I made _stop_line, lane_ and _lights_ using [assuremappingtools](https://github.com/hatem-darweesh/assuremappingtools/) refer to tutorials on [youtube](https://www.youtube.com/watch?v=kb2U9jeqr7M&list=PLVAImlqqGbr4G8GXMsqp6dMhbKxTCEnrh&index=4).
![assure](https://user-images.githubusercontent.com/35717400/95707568-d4cf9880-0c94-11eb-9d1f-5019598c8003.png)

I want to use this .kml file in  _open planner 2.0_.
Is there any documents or tutorials for how to connect all ids correctly between light-lane-stopline using [assuremappingtools](https://github.com/hatem-darweesh/assuremappingtools/) ?

Thanks in advance.

**Comment by hatem-darweesh** [comment]
Sorry for the late reply, 

Just check the available information in the traffic light, stop line. 

one more thing, 
select the closest waypoint to the stop line, 
then enter the stop line ID.
