### ISSUE TITLE
If mesa-utils is not installed, build-docker.sh fails

### ISSUE THREAD

**Issue by JWhitleyWork** [hatem-darweesh/assuremappingtools#34]
If the package `mesa-utils` is not installed on the host system, the call to `glxinfo` in the `build-docker.sh` script fails. This is not immediately apparent as the actual Docker build doesn't fail until it tries to move the `.run` file for the driver.

**Comment by hatem-darweesh** [comment]
Thanks @JWhitleyWork , any suggestions? 
I am a beginner with docker.

**Comment by Aladdin-Ark** [comment]
The current master branch is updated to  exit the build script in case `glxinfo` failed to run.
Also the README is updated to have `mesa-utils` as one of the requirements to use the build script.

**Comment by hatem-darweesh** [comment]
Thanks @Aladdin-Ark
