### ISSUE TITLE
new script docker error

### ISSUE THREAD

**Issue by sethut** [hatem-darweesh/assuremappingtools#38]
![Screenshot from 2021-01-11 22-14-55](https://user-images.githubusercontent.com/40734644/104186906-71ebca00-545a-11eb-9411-f55a74dcba46.png)

with new script, zatitech/assuremappingtools not found error. maybe image and tag name is wrong

**Comment by sethut** [comment]
> can you check the docker images you have

thanks. it just my fault

**Comment by ayberksener** [comment]
@sethut @hatem-darweesh 
I am getting the same error, can you please guide me how you resolve this issue. Thank you

**Comment by sethut** [comment]
> @sethut @hatem-darweesh
> I am getting the same error, can you please guide me how you resolve this issue. Thank you

just run build script first
I misunderstood as docker pull is operating  when executing a run script

if you have an error, check the image
$docker images
if you don't have an image zatitech/assuremappingtools:master, docker image is not build yet
but if you have an image above, i don't know about that. that's not same issue

**Comment by sethut** [comment]
@ayberksener 
just run build script first
I misunderstood as docker pull is operating when executing a run script

if you have an error, check the image
$docker images
if you don't have an image zatitech/assuremappingtools:master, docker image is not build yet
but if you have an image above, i don't know about that. that's not same issue
