### ISSUE TITLE
about lane merge and delete error lane

### ISSUE THREAD

**Issue by TerryLSR** [hatem-darweesh/assuremappingtools#43]
hello,
my ASSURETOOLS ver is 0.5, but it can not delete the error lane. The DELETE button is not useful. 
And if I want to merge one lane to anther lane, the value of "to Points" or " to Lane" is can  not be setted.
 Is there  some way to solve these problems?
![image](https://user-images.githubusercontent.com/33231393/109273505-4166c080-784d-11eb-856e-2989df5641b5.png)

Thanks.

**Comment by hatem-darweesh** [comment]
To delete lane you select the lane (not the waypoint) , then press Ctrl + d + d 
to add item in the Info View: 
Add: '+' 
Delete: 'Delete' button

**Comment by TerryLSR** [comment]
The operation that you asid to delete lane is useful ! thanks.
but how to merge one lane to anther lane, the value of "To Points" or " To Lane" is can not be setted.

**Comment by hatem-darweesh** [comment]
Can you show me example by recording a video.

**Comment by athulg** [comment]
> The operation that you asid to delete lane is useful ! thanks.
> but how to merge one lane to anther lane, the value of "To Points" or " To Lane" is can not be setted.

I've the exact same issue, I'm unable to manually enter any values in the "To Lanes" or "From Lanes" value box. The delete operation worked perfectly.

Thanks

**Comment by hatem-darweesh** [comment]
Sorry I can not understand the issue with editing from a picture.
