### ISSUE TITLE
Any plan to generate Autoware Lanelet2 OSM file from Open Street Map exported file directly.

### ISSUE THREAD

**Issue by privvyledge** [hatem-darweesh/assuremappingtools#46]
I have an Open Street Map file downloaded from https://www.openstreetmap.org/. 

1. Do you have any plan to load these .osm files (not Lanelet2)?
2. How can I generate a standard Lanelet2 .osm map from the Open Street Map .osm map?
3. How can I generate an Autoware compatible Lanelet2 .osm map?

Thanks for your help.

**Comment by hatem-darweesh** [comment]
there is a converter from Open Street Map .osm file to OpenDRIVE. 
check this link 
https://sumo.dlr.de/docs/Tutorials/Import_from_OpenStreetMap.html

**Comment by privvyledge** [comment]
I have tested that converter. I then loaded the OpenDRIVE map into assuremapping tools successfully and saved it as a Lanelet2 file. However, I kept getting the same error as shown in issue https://github.com/hatem-darweesh/assuremappingtools/issues/45. Thanks.

**Comment by felixf4xu** [comment]
> there is a converter

what's the name of the converter? I can't find OpenDrive related information in the page
