### ISSUE TITLE
Using generated Autoware Lanelet2 map.

### ISSUE THREAD

**Issue by privvyledge** [hatem-darweesh/assuremappingtools#47]
I downloaded the sample Autoware lanelet2 map (I am running into problems with my own map. See https://github.com/hatem-darweesh/assuremappingtools/issues/45#issue-831223040) and loaded it into assuremappingtools then saved it as a Lanelet2 map. However, I have some questions about loading it:

**Comment by hatem-darweesh** [comment]
so , you want to know how to use Autoware ? 
please check the online documentation, tutorials and videos that has the answers. 
It will take long time and huge effort to answer these question.

**Comment by privvyledge** [comment]
I have done so but the documentation is incomplete and does not directly provide these answers. I will ask them in the appropriate channel though.

Thanks.
