### ISSUE TITLE
LaneLet2 map is loading up  not correctly

### ISSUE THREAD

**Issue by ParthAD3** [hatem-darweesh/assuremappingtools#51]
hello, 

i am loading my .xodr file and then saving it in .osm (Lanelet2) format, and  when i load that saved file the road lines are broken and the traffic lights (Green dots ) are out of the whole map, its seems to be broken, can you help with this issue ?

![Screenshot from 2021-04-30 11-12-56](https://user-images.githubusercontent.com/71602780/116674964-920dad80-a9a5-11eb-9f2d-8efdac76b265.png)
![Screenshot from 2021-04-30 11-13-16](https://user-images.githubusercontent.com/71602780/116674966-92a64400-a9a5-11eb-860e-c22fe5ba1461.png)
![Screenshot from 2021-04-30 11-13-25](https://user-images.githubusercontent.com/71602780/116674969-933eda80-a9a5-11eb-9d50-f4b96f461fc1.png)
![Screenshot from 2021-04-30 11-13-34](https://user-images.githubusercontent.com/71602780/116674971-933eda80-a9a5-11eb-8a70-d888358deb0a.png)

**Comment by ParthAD3** [comment]
i seem to have fixed the issue of broken lane lines but i am unable to fix the traffic lights going out of the map on the left side (Refer last image )

**Comment by hatem-darweesh** [comment]
Hi @ParthAD3 , This issue was fixed with the latest commit. 
git the latest from "master" and check again.

**Comment by ParthAD3** [comment]
Hey, i seems to be now working still, as you can see i am in the git master branch
![16200589257864531278621222084894](https://user-images.githubusercontent.com/71602780/116903459-b9ca7300-ac3c-11eb-915a-0ab0e3f50a7a.jpg)

**Comment by hatem-darweesh** [comment]
1- load the OpenDRIVE .xodr map 
2- remove the projection string from the map info dialog 
3- save to lanelet2 .osm map

**Comment by ParthAD3** [comment]
> 1- load the OpenDRIVE .xodr map
> 2- remove the projection string from the map info dialog
> 3- save to lanelet2 .osm map

Yes, i have executed these steps just as mentioned, also i have un select the show all roads.
After saving, when i load the labeler.osm file to check it, it loads up as the above image.

**Comment by hatem-darweesh** [comment]
You need to rebuild docker

**Comment by hatem-darweesh** [comment]
@ParthAD3 were you able to get it to work ?

**Comment by ParthAD3** [comment]
hey @hatem-darweesh 
so, i rubuilt the docker, now the updates are,
1. the traffic light are in their position now i.e. in the maps but i have 1 ques regarding the traffic lights : 
> what does the horizontal angle of the traffic light (the arrows) mean, is it the traffic light direction (the facing of the tfl) to the traffic or something else because when i loaded the .xodr map the horizontal directions are different from the lanelet2.osm map direction (refer image)
![Screenshot from 2021-05-14 11-46-48](https://user-images.githubusercontent.com/71602780/118259711-c1e2a800-b4b1-11eb-9254-6a6864bca8b8.png)
the .xodr traffic light horizontal position (i don’t understand their horizontal position please explain) also in the right side of the image the two parallel gray stopping lines seems a bit wrong than the others
![Screenshot from 2021-05-14 12-43-59](https://user-images.githubusercontent.com/71602780/118260003-184fe680-b4b2-11eb-8a67-1b3bfcceda5c.png)


2. in this lanelet2 map i don’t have the other road boundaries in the map which were there in the .xodr map, and it seems they were not present in the previous update aswell you can refer the image above(which was having the traffic light issue)  
> what i want is the white boundries line and the yellow middle lines as image below.
![Screenshot from 2021-05-14 12-35-00](https://user-images.githubusercontent.com/71602780/118260311-6c5acb00-b4b2-11eb-97aa-3300af720401.png)


can these things  from point 2. be implemented then that’ll be perfect, and please explain my point 1. question. Thankyou

**Comment by hatem-darweesh** [comment]
Can you make your question simpler and shorter, I don't understand what is the problem
for you information: 
- traffic light angle is wrong in the OpenDRIVE map 
- .xodr doesn't have stop line, only something called traffic light reference point, I use these points to create fake stop lines. 
- not everything in OpenDRIVE are supported in lanelet2 , so don't expect full conversion. 
-

**Comment by ParthAD3** [comment]
ok, question:
1. what does the traffic light horizontal angle in the lanelet2 map mean. does it show the face of the traffic light  towards the traffic?
![Screenshot from 2021-05-14 11-46-48](https://user-images.githubusercontent.com/71602780/118269758-63bcc180-b4bf-11eb-868b-30a22f5f2def.png)
2. so, you mean to say that there wont be the white and the yellow lines from the .xodr converted in the loaded lanelet2 map ? because we needed those lane boundaries the yellow and the white outer ones, rest features we are ok with

**Comment by hatem-darweesh** [comment]
1. Yes, it matches the traffic direction. even if the traffic light "yaw" in the OpenDRIVE is correct. lanelet2 map format does not support traffic light heading. (if you know otherwise please tell me). 
2. Sorry, the "lineStringLayer" which can represent lane markings in the lanelet2 map is not supported in the tool now, I will add it to the tasks list.

**Comment by ParthAD3** [comment]
Basically, I could generate the Lanelet2 map and convert it to Vector Map using lanelet_aisan_converter. But the generated traffic light poles have a slightly different position comparing to the original ones and also all three lights arrows Blue, Yellow and Red are on the same position. So I can only see one.
Do you know what can I do to solve it?
