### ISSUE TITLE
Custom map origin

### ISSUE THREAD

**Issue by BatuhanUlucay** [hatem-darweesh/assuremappingtools#54]
I want to change the position of initial origin (or grid). Because when I load my pointcloud to the tool, I want to align my origin to somewhere I know. Is this possible?

Also is there any documentation about the projection section?

Thanks in advance

**Comment by hatem-darweesh** [comment]
You will find new menu item called "shift map" which does exactly what you asked for. 
About projection, you will find only plenty of articles about projection coordinates, tools, libraries. 
In assuremappingtool I use libproj4 as the tool to calculate UTM from GPS and vice versa. 
also check the project readme.

**Comment by BatuhanUlucay** [comment]
Thank you for the update! Do you mean translate map button with "shift map" ? It translates map items, but can I shift the pointcloud based on origin grid? Thanks.

**Comment by hatem-darweesh** [comment]
Hi @BatuhanUlucay , similar function can be added. 
can you convince me why this function should be included. 
what I understand, if your point cloud map has wrong origin, you have to re-generate this map with accurate origin (pose + rotation).

**Comment by BatuhanUlucay** [comment]
Hello again @hatem-darweesh 
I am importing my pointcloud, tool is putting a grid to the center of the pointcloud, but I cannot obtain the accurate position and rotation for that origin. I want to shift the whole map (and pointcloud) to the point where I know the position(my own origin).
Thanks for the quick answers!

**Comment by hatem-darweesh** [comment]
Can you open separate issue for this function. and tell me what coordinates system are you targeting.

**Comment by BatuhanUlucay** [comment]
[new issue](https://github.com/hatem-darweesh/assuremappingtools/issues/57)

**Comment by congphase** [comment]
Hi all, is there any update on this?
