### ISSUE TITLE
map-export-problem

### ISSUE THREAD

**Issue by ali-mehran-adastec** [hatem-darweesh/assuremappingtools#6]
@hatem-darweesh, Tnx for your tool first of all. I'm currently using "Assure Map Editor v0.1" and I have several problems with it which i wanna mention them here: 

1- My main problem is that the only format program can export is '.kml' and it cannot output '.osm' file format. So next problems are in the .kml, the only format that i can obtain: 

2- While adding "Traffic light" primitive, the editor cannot save the angle of traffic light. It saves it but when next time trying to open the created map, horizental and vertical angles change to the default 0 again.
3- Third, when I add "traffic sign" primitive to map, later on I cannot open the map file again and the editor suddenly quits.​

**Comment by hatem-darweesh** [comment]
Issues fixed. 
In addition, now you can load and save lanelet2 .osm file with GPS origin. 
the projection is UTM. 
please check.
