### ISSUE TITLE
How to copy and paste a previously created lane

### ISSUE THREAD

**Issue by d0l1v3** [hatem-darweesh/assuremappingtools#72]
Hi,

is there a way to copy and paste a previously created lane? I'd like to copy a lane I generated to use it multiple times to save me some time.

Thanks in advance!
Best regards.

**Comment by hatem-darweesh** [comment]
Thank you for your comment
Sorry, 
Currently copy and past feature is not working properly. 
I shall add this to the future task list.

**Comment by d0l1v3** [comment]
Alright, thank you for your fast reply. Then I will close this issue for now.
