### ISSUE TITLE
Dependencies aren't fully outlined

### ISSUE THREAD

**Issue by mjshiggins** [hatem-darweesh/assuremappingtools#9]
I'm attempting to containerize this application in Docker, but the dependency list seems to be incomplete. I'd like to investigate further but am unable to due to Issue #8 and lack of code. Happy to help be a contributor here to get this running smoothly in Docker.

UPDATE EDIT:
I was able to configure a Docker environment that can run the 16.04 / master version. Will submit a PR.

**Comment by hatem-darweesh** [comment]
@mjshiggins WOW , that is great, thanks a lot, 
btw I added native [ubuntu 18.04 build ](https://github.com/hatem-darweesh/assuremappingtools/tree/ubuntu18.04_build). 

what this project needs is a proper linux installer container.

**Comment by mjshiggins** [comment]
Closing due to closed source: https://github.com/hatem-darweesh/assuremappingtools/issues/8#issuecomment-625783723
